project:
  type: website
  output-dir: docs

website:
  title: "Goated_Website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: FYP Project
      - href: newpage.qmd
        text: Data Visualisation
      - href: new2.qmd
        text: Reflection

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



